// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
    if(license !== "none"){
        return `![Github License](https://img.shields.io/badge/Github%20License-${license}-green.svg)`
        
    }
    return '';
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
    if(license !== 'none'){
        return `\n* [License](#license)\n`
    }
    return '';
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
    if(license !== 'none'){
        return `## License
        
            Licensed under ${license} license`
    }

    return '';
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}
    by ${data.name}

    As an asynchronous event-driven JavaScript runtime, Node.js is designed to build scalable network applications, 
    through which many connections can be handled concurrently, allowing the user to request different callback functions 
    symultanously and work locally without depending necessarily on the browser.

    Developers most of the times will be required to build BackEnd applications and contained professional README files that 
    will work as their cover to better describe their knowledge. Above, there's a README file generated by Node and the terminal 
    by answeing the prompts printed in the console.

   ${renderLicenseBadge(data.license)}
   ## Table of Contents
   [Description](#description)
   [Installation](#installation)
   [Usage](#usage)
   [Contributions](#contributions)
   [Functionality](#functionality)
   [Contact-Me](#email)
   [License](#license)

   ${renderLicenseLink(data.license)}
   ## Description
   ${data.description}
   ## Functionality
   ${data.functionality}

   ## Installation
   ${data.installation}
   ## Usage
   ${data.usage}
   ## Contributors
   ${data.contributions}

   ## Contact-Me
    \nName: ${data.name}
    \nEmail: ${data.email}
    \nGithub: ${data.github}

   ${renderLicenseSection(data.license)} 

   ## Link to the Google Drive Video
   https://drive.google.com/file/d/1KP9eR4p85SgNIRkfJT3m9FRZfSRHl-a5/view
`;
}

module.exports = generateMarkdown;
